name: Initiate Pre-Release

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  workflow_dispatch:

jobs:
  setup:
    name: Generate Version
    runs-on: ubuntu-latest
    if: startsWith( github.event.head_commit.message, 'feat' ) || startsWith( github.event.head_commit.message, 'fix' ) || contains(github.event.head_commit.message, '!:') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.5.1

  pre-release:
    if: github.event_name == 'push'
    needs: [setup]
    uses: ./.github/workflows/pre_release.yml
    with:
      publishTag: "next"
      versionFormat: "${major}.${minor}.${patch}-prerelease${increment}"
    secrets: inherit

  dev-release:
    if: github.event_name == 'workflow_dispatch'
    needs: [setup]
    uses: ./.github/workflows/pre_release.yml
    with:
      publishTag: "dev"
      versionFormat: "${major}.${minor}.${patch}-${{ github.event.base_ref }}${increment}"
    secrets: inherit