name: Test NPM packages
on: [pull_request]

jobs:
  test-functions-runtime:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: functions-runtime
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./packages/functions-runtime
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: ./packages/functions-runtime
        run: pnpm run test

  test-testing-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - uses: actions/checkout@v3
      - name: Install deps
        working-directory: ./packages/testing-runtime
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: ./packages/testing-runtime
        run: pnpm run test

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2 # vscode (electron) uses this so we want to make the tests use a comparable environment
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: Install Go deps
        run: go mod download
      - name: Generate wasm binary
        run: make wasm
      - name: Install package deps
        working-directory: ./packages/wasm
        run: pnpm install --frozen-lockfile
      - name: Run tests
        working-directory: ./packages/wasm
        run: pnpm run test
